name       : sigrok-cli
version    : 0.7.1
release    : 5
source     :
    - https://sigrok.org/download/source/sigrok-cli/sigrok-cli-0.7.1.tar.gz : f52413429f47d457c333db0fd068416ab7a3f9e35ca76de8624dc5ac6fb07797
license    : GPL-3.0-or-later
component  : programming.tools
summary    : A command-line tool that interfaces with various signal analyzers
description: |
    sigrok-cli is a command-line tool written in C, which uses both libsigrok and libsigrokdecode to provide the basic sigrok functionality from the command-line. Among other things, it's useful for scripting purposes.
builddeps  :
    - pkgconfig(libsigrok)
    - pkgconfig(libsigrokdecode)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
