name       : sigrok-cli
version    : 0.7.0
release    : 1
source     :
    - http://sigrok.org/download/source/sigrok-cli/sigrok-cli-0.7.0.tar.gz : 5669d968c2de3dfc6adfda76e83789b6ba76368407c832438cef5e7099a65e1c
license    : GPL-3.0
component  : programming.tools
summary    : A command-line tool that interfaces with various signal analyzers
description: |
    sigrok-cli is a command-line tool written in C, which uses both libsigrok and libsigrokdecode to provide the basic sigrok functionality from the command-line. Among other things, it's useful for scripting purposes.
builddeps  :
    - pkgconfig(libsigrok)
    - pkgconfig(libsigrokdecode)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
